LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes       # Mouse keys
COMMAND_ENABLE = no        # Commands for debug and configuration
RGBLIGHT_ENABLE = no       # Enable WS2812 RGB underlight.

UNICODE_ENABLE = yes
OLED_DRIVER_ENABLE = no
AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = yes
TAP_DANCE_ENABLE = yes
#AUTOCORRECT_ENABLE = yes
